In [7]:
import sys
!{sys.executable} -m pip install numpy
!{sys.executable} -m pip install matplotlib

import matplotlib.pyplot as plt
import numpy as np

In [6]:
G = 6.6743E-11

def norm(p1, p2):
    return np.sqrt((p1[0]-p2[0])**2 + (p1[1]-p2[1])**2 + (p1[2]-p2[2])**2)

def acceleration(p1, p2, p3, m1, m2, m3):
    a1 = (-G*m2*((p1-p2)/norm(p1,p2)**3)) - (G*m3*((p1-p3)/norm(p1,p3)**3))
    a2 = (-G*m3*((p2-p3)/norm(p2,p3)**3)) - (G*m3*((p2-p1)/norm(p2,p1)**3))
    a3 = (-G*m1*((p3-p1)/norm(p3,p1)**3)) - (G*m3*((p3-p2)/norm(p3,p2)**3))
    return a1, a2, a3

m1, m2, m3 = 6E24, 6E24, 6E24

p1 = np.array([1, 2, 3])
p2 = np.array([6, 9, 1])
p3 = np.array([7, 2, 5])
a1, a2, a3 = acceleration(p1, p2, p3, m1, m2, m3)
a1, a2, a3

(array([1.24042941e+13, 4.06923817e+12, 2.00325899e+12]),
 array([-2.15973548e+12, -9.29728069e+12,  4.15009234e+12]),
 array([-1.02445586e+13,  5.22804252e+12, -6.15335133e+12]))